services:
  delivery:
    container_name: delivery-service
    build:
      context: ./delivery
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      - microservices
  users:
    container_name: users-service
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      - microservices

networks:
  microservices:
    external: true
