services:
  delivery:
    image: delivery-service:latest
    container_name: delivery-service
    build:
      context: ./delivery
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      - microservices
  users:
    image: users-service:latest
    container_name: users-service
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      - microservices
  gateway:
    image: gateway-service:latest
    container_name: gateway-service
    build:
      context: ./krakend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
    restart: always
    networks:
      - microservices

networks:
  microservices:
    external: true
